### ISSUE TITLE
"Stock Browser", but "SamsungBrowser"

### ISSUE THREAD

**Issue by mrDoctorWho** [pieroxy/java-user-agent-detection#13]
I personally don't consider this a correct way to represent the browser's name. The format for all names should be identical. If you use spaces in one name, you should use it in another.

**Comment by pieroxy** [comment]
Interesting point. I'll try to make a pass of cleaning. For the record, do you have any preference ?

**Comment by mrDoctorWho** [comment]
Stock, Samsung, etc.

I mean, maybe there shouldn't be a Browser in the name? This is a browser name. If someone wanted, they would add "Browser" in the name by themselves in an upper level.

Same for BrowserFamily.

**Comment by pieroxy** [comment]
Makes perfect sense :) 

These are leftovers of an era in which the results were just a bunch of strings without a proper structure.

**Comment by pieroxy** [comment]
Fixed in the latest commit. Thanks for the feedback.
