### ISSUE TITLE
Braces in brand names

### ISSUE THREAD

**Issue by mrDoctorWho** [pieroxy/java-user-agent-detection#14]
> (Windows)
> (Linux)
> (Unix-like)

Why?

**Comment by pieroxy** [comment]
I didn't know what to put in there. I really have no brand to put. I should just leave it empty I guess.

**Comment by mrDoctorWho** [comment]
Well, let's think about this.

When does this happen?

**Comment by mrDoctorWho** [comment]
```java
UNKNOWN(""),
```

I think it should be unknown string too. The point is that the upper level (the program that uses your library) could easily guess that the library has no idea about the browser/brand/etc name.

**Comment by mrDoctorWho** [comment]
```java
OPENSOURCE("An Open Source Project"),
```

Is that even a thing?

**Comment by pieroxy** [comment]
Well, yes and no. I wanted to distinguish the case where a brand is unknow from the case where there is structurally no brand because the project is a collaborative project. Maybe I should add an `enum ProjectType { COMMERCIAL, OPEN_SOURCE }`

**Comment by mrDoctorWho** [comment]
@pieroxy enum is a good idea, love it.

**Comment by pieroxy** [comment]
Fixed with the last two commits. Let me know if the solution works for you.
