### ISSUE TITLE
The brand can apply to Browsers, Devices or OSes

### ISSUE THREAD

**Issue by mrDoctorWho** [pieroxy/java-user-agent-detection#15]
I think, there should be a separate class for each of the above. So it will be easier to add new or edit items.

What do you think, @pieroxy?

**Comment by pieroxy** [comment]
I don't see the point of having separate enums: BrowserBrand, DeviceBrand, etc... Google makes Android, ChromeOs and Chrome. It is the same Google.

In my view it would amount to duplicate information.

What is complex about adding or editing an item in the enum ?

**Comment by pieroxy** [comment]
(FYI, I'm going to make a release this week. I'll try to incorporate as many changes as I can.)

**Comment by mrDoctorWho** [comment]
> What is complex about adding or editing an item in the enum ?

That's probably not the only reason.

What if one day Chrome changes it's name? Anyway, I think it's a good idea to have different things in different classes.

**Comment by pieroxy** [comment]
If Chrome change it's name it'll be handled just like Edge which is the new name of IE. The brand will still be microsoft, which is the same brand as Windows, because it's the same company. 

>Anyway, I think it's a good idea to have different things in different classes.

Microsoft is one company producing browsers and operating systems. It's one thing. Why should we have it in different enums ?

**Comment by pieroxy** [comment]
Any comments about my last remark ? 

If not I'll just close this item.

**Comment by mrDoctorWho** [comment]
I see your point. And I think it might be right. 

Closing this.
