### ISSUE TITLE
Single double quote

### ISSUE THREAD

**Issue by cdclaxton** [pieroxy/java-user-agent-detection#20]
If the user-agent is an (invalid) single double quote, the code at line 16 in 

https://github.com/pieroxy/java-user-agent-detection/blob/master/src/main/java/net/pieroxy/ua/detection/UserAgentContext.java

will cause a String out-of-bounds (-1) exception.

**Comment by pieroxy** [comment]
Thanks. I will fix this in the next release.

**Comment by pieroxy** [comment]
The code is in. Next release will happen shortly.
