### ISSUE TITLE
Don't throw NullPointerException if input is null

### ISSUE THREAD

**Issue by ceefour** [pieroxy/java-user-agent-detection#21]
To make it easy to just pass whatever `request.getHeader("User-Agent")` returns.

**Comment by pieroxy** [comment]
Hello. 

I am not sure I understand your issue. There is no notion of a request in the library. Could you detail a bit further the issue ?

**Comment by ceefour** [comment]
that was just an example, anyway just make sure that passing null is same as empty string

**Comment by pieroxy** [comment]
Ok, thanks. The code is in. Will be released along with the next release.
