### ISSUE TITLE
Google Structured Data Testing Tool crawler not recognised as a BOT

### ISSUE THREAD

**Issue by shurizzle** [pieroxy/java-user-agent-detection#3]
User Agent "Mozilla/5.0 (compatible; Google-Structured-Data-Testing-Tool +http://developers.google.com/structured-data/testing-tool/)" isn't recognised as a BOT. Please add it to list.

**Comment by pieroxy** [comment]
Thanks

**Comment by pieroxy** [comment]
in the next release

**Comment by pieroxy** [comment]
Hmmm. I messed up something. Will be in the newt release next weekend.

Sorry about that.
