### ISSUE TITLE
Adword Mobile crawler recognised as an iPhone

### ISSUE THREAD

**Issue by shurizzle** [pieroxy/java-user-agent-detection#4]
User Agent "Google-Adwords-Instant-Mobile (+http://www.google.com/adsbot.html) Mozilla (iPhone; U; CPU iPhone OS 3 0 like Mac OS X) AppleWebKit (KHTML, like Gecko) Mobile Safari" recognised as an iPhone while it's a Robot.

**Comment by pieroxy** [comment]
Thanks. Will get to it this weekend.

**Comment by pieroxy** [comment]
Done
