### ISSUE TITLE
Some other google bots not recognised

### ISSUE THREAD

**Issue by shurizzle** [pieroxy/java-user-agent-detection#5]
Please see list at https://support.google.com/webmasters/answer/1061943

* Googlebot/2.1 (+http://www.google.com/bot.html)
* Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

**Comment by pieroxy** [comment]
Will be in the next version

**Comment by pieroxy** [comment]
Done
