### ISSUE TITLE
cUrl default UA and another bot unrecognised

### ISSUE THREAD

**Issue by shurizzle** [pieroxy/java-user-agent-detection#8]
Hi, today I've some cUrl uas not recognised. See

```
curl/7.35.0 (nic.it crawler)
curl/7.38.0
curl/7.43.0
```

And a new bot with ua `ia_archiver`. More infos on https://support.alexa.com/hc/en-us/articles/200450194-Alexa-s-Web-and-Site-Audit-Crawlers

Thanks :+1:

**Comment by pieroxy** [comment]
Fixed in the latest commit. Will be released shortly. Sorry for the delay :-(
